# Generated by Django 2.2.1 on 2019-05-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainforest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descriptiion',
        ),
    ]
