# Generated by Django 2.2.1 on 2019-05-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainforest', '0002_auto_20190530_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
